public/templates/mv/css/custom.css
public/templates/mv/teste_button.html
resources/views/committees/meioambiente.blade.php
resources/views/committees/teste.html
resources/views/home/index.blade.php
resources/views/layouts/master.blade.php
resources/views/partials/committee-telephone.blade.php
resources/views/partials/footer.blade.php
resources/views/partials/header.blade.php
resources/views/partials/scripts.blade.php
resources/views/partials/telefones-uteis.blade.php

Update Clean CSS

---

app/Data/Models/Progress.php
app/Http/Requests/PersonAddressesRequest.php
app/Services/ImportCercred.php
database/factories/ProgressFactory.php

https://github.com/alerj/aloalerjsite/issues/226

Acentos da importação

---

app/Data/Models/BaseModel.php
app/Data/Repositories/People.php
composer.json
composer.lock

Issue #239 
Vai precisar:
- composer install
- Em .env, usar o parâmetro **CACHE_DRIVER=redis**

Flushing search caches after saving anything

---

app/Data/Models/PersonAddress.php
app/Http/Controllers/PersonAddresses.php
database/migrations/2018_08_24_100001_alter_table_person_addresses.php
resources/views/callcenter/person_addresses/form.blade.php
resources/views/callcenter/person_addresses/index.blade.php

https://github.com/alerj/aloalerjsite/issues/241
https://github.com/alerj/aloalerjsite/issues/245

Ao clicar em um endereço a página veio com dados vazios && Criar coluna para número no endereço

---

app/Data/Repositories/People.php
app/Http/Controllers/PersonContacts.php
app/Http/Requests/RecordRequest.php
resources/views/callcenter/person_contacts/form-workflow.blade.php

Issues:  #225 #240 #243

---

app/Data/Repositories/Records.php

Fixed markAsResolved

---

app/Services/ImportCercred.php
public/js/app.js
resources/assets/js/apps/addresses.js

Changed focus after CEP

---

app/Http/Controllers/PersonContacts.php
app/Http/Requests/PersonContactsWorkflowRequest.php
app/Rules/Contact.php
public/js/app.js
resources/assets/js/apps/contacts.js
resources/views/callcenter/person_contacts/form-workflow.blade.php

Issue about workflow contacts

---

app/Data/Models/PersonAddress.php
app/Data/Models/PersonContact.php
app/Data/Presenters/PersonAddress.php
app/Data/Presenters/PersonContact.php
database/migrations/2018_08_30_202359_add_active_columns_to_addresses_and_contacts.php
resources/views/callcenter/person_addresses/form.blade.php
resources/views/callcenter/person_addresses/index.blade.php
resources/views/callcenter/person_contacts/form.blade.php
resources/views/callcenter/person_contacts/index.blade.php

Added active state to Address and Contact

---

app/Data/Models/Progress.php
app/Data/Presenters/Base.php
app/Data/Presenters/Progress.php
app/Data/Repositories/Records.php
app/Http/Controllers/CallCenter/Progresses.php
database/migrations/2018_09_03_150000_alter_record_table_add_resolve_progress_id_column.php
resources/views/callcenter/progress/partials/table.blade.php
resources/views/callcenter/records/form.blade.php

Issue #274 https://github.com/alerj/aloalerjsite/issues/274

Bug no Protocolo e Andamento Finalizador

---

app/Data/Repositories/People.php
database/migrations/2018_09_03_170000_create_extension_unaccent.php

https://github.com/alerj/aloalerjsite/issues/280

Busca sem acentos

---

app/Data/Repositories/BaseRepository.php
database/migrations/2018_09_04_190000_update_name_areas.php

https://github.com/alerj/aloalerjsite/issues/287

 Order Name + Trim 

---

resources/views/callcenter/records/partials/table.blade.php

Acrecentar nome da pessoa na <table> "não resolvidos"

---

app/Http/Requests/PersonContactsWorkflowRequest.php
public/js/app.js
resources/assets/js/apps/search.js
resources/views/callcenter/person_contacts/form-workflow.blade.php

Não mostrar alerts de erro duplicados #298 e Campo nome NULL #299

Não mostrar alerts de erro duplicados #298 e Campo nome NULL #299

---

app/Http/Requests/PersonAddressesRequest.php
resources/views/callcenter/person_addresses/form.blade.php

Campo Número de Endereço é um campo string.

Campo Número de Endereço é um campo string.

---

database/migrations/2018_09_24_160000_convert_protocol_and_phone_only_number.php

Remover formatação de protocolo e telefone do banco de dados #377

Remover formatação de protocolo e telefone do banco de dados #377

---

app/Data/Repositories/People.php
app/Http/Requests/Contact.php
app/Support/helpers.php
public/js/app.js
public/mix-manifest.json
resources/assets/js/apps/contact-form.js
resources/views/contact/index.blade.php

Criar validações para formulário de contato #383

Criar validações para formulário de contato #383

---

public/js/app.js
public/mix-manifest.json
resources/assets/js/apps/addresses.js
resources/views/callcenter/person_addresses/form.blade.php

Fallha no carregamento das informações da página de endereços #408

Fallha no carregamento das informações da página de endereços #408

---

app/Data/Repositories/Notifications.php
app/Http/Controllers/CallCenter/Progresses.php
app/Services/ImportCercred.php
public/js/app.js
public/mix-manifest.json
resources/assets/js/apps/contacts.js
resources/views/callcenter/committees/form.blade.php
resources/views/callcenter/person_contacts/form-workflow.blade.php
resources/views/callcenter/records/form.blade.php
resources/views/callcenter/records/show-protocol.blade.php

Problema com formatação de campos de telefone #439 
@brenot 
@antonioribeiro

 Problema com formatação de campos de telefone #439

---

database/seeds/CommitteesSeeder.php
license

Production 

---

app/Committee.php

fix comite

---

resources/views/auth/login.blade.php
resources/views/callcenter/records/partials/table.blade.php
resources/views/pages/aloalerj.blade.php

Atualizações AloAlerj

---

app/Data/Repositories/Committees.php
app/Http/Controllers/CallCenter/Committees.php
app/Http/Controllers/Pages.php
app/Http/Requests/CommitteeRequest.php
resources/views/callcenter/committees/form.blade.php
resources/views/committees/show.blade.php
resources/views/pages/aloalerj.blade.php
resources/views/pages/committees.blade.php
routes/web.php

ISSUE #496

---

app/Data/Repositories/Records.php
resources/views/callcenter/records/advanced-search.blade.php

Adição da opção de selecionar um intervalo de datas nos campos de busca avançada.

Issue #475

---

database/migrations/2019_11_12_135723_add__cultura_option_to_area.php

Adição da opção cultura ao campo Área

---

app/Http/Controllers/CallCenter/Records.php

Order areas

---

database/migrations/2020_02_07_104133_add_deputados_option_to_area.php

Adição da opção Deputados ao campo Área ISSUE #543

---

app/Http/Requests/CommitteeRequest.php

Issue #570 .
Removi a obrigatoriedade dos campos que estão apresentando erro e parece que isso já foi suficiente para o fluxo voltar a normalidade.
Estou verificando se isso pode gerar algum efeito colateral, peço que não upe as mudanças de imediato.

ISSUE #570

---

app/Data/Models/CommitteeService.php
app/Http/Controllers/Services.php
database/migrations/2020_06_30_120100_add_collumns_phone_and_email_to_committee_service.php
database/migrations/2020_07_07_101528_add_phone_to_table_services.php
resources/views/callcenter/committee_services/form.blade.php
resources/views/pages/committees.blade.php
resources/views/services/show.blade.php
routes/web.php

Issue #572

---

resources/views/partials/commitees-links-1.blade.php

ajuste de links - footer - Issue #572

---

resources/views/pages/aloalerj.blade.php

Alteração do texto de descrição #issue593

---

resources/views/partials/telegram-icons.blade.php

Change app icon links

---

resources/views/pages/aloalerj.blade.php
resources/views/partials/form-chat-offline.blade.php

Alterações de textos para os padrões Issue #630

---

app/Http/Requests/RecordRequest.php
resources/views/callcenter/progress/form.blade.php
resources/views/callcenter/progress/partials/table.blade.php
resources/views/callcenter/records/advanced-search.blade.php
resources/views/callcenter/records/form.blade.php
resources/views/callcenter/records/partials/table.blade.php
resources/views/callcenter/records/show-public.blade.php

#617 e #621

---

public/templates/mv/css/custom.css
resources/views/services/show.blade.php
routes/web.php

Issue #728

---

resources/views/pages/aloalerj.blade.php
resources/views/partials/form-chat-offline.blade.php

alteração do horário de funcionamento

alteração do horário de funcionamento

---

resources/views/pages/aloalerj.blade.php
resources/views/partials/form-chat-offline.blade.php

Ajuste horário de atendimento para de 10 às 17h

Ajuste horário de atendimento para de 10 às 17h

---

app/Data/Repositories/Records.php

Correção de protocolo enviado por email

Issue: #680

---

app/Data/Repositories/Records.php
resources/views/callcenter/records/advanced-search.blade.php

Issue #794

---

composer.json
composer.lock

update package whoops

---

composer.json
composer.lock

Dusk Update
